apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-green
  namespace: nginx-green
spec:
  hosts:
  - "nginx.com"
  gateways:
  - gateway-green
  http:
  - route:
     - destination:
        host: nginx
        subset: green


