apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-stable
  namespace: nginx-stable
spec:
  hosts:
  - "stable.nginx.com"
  gateways:
  - gateway-stable
  http:
  - route:
     - destination:
        host: nginx
        subset: stable
