apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-release-1000
  namespace: nginx-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name: nginx-release-1000
        image: xeng/nginx-stable:latest
        ports:
        - containerPort: 80
