apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-1
  namespace: nginx-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: blue
  template:
    metadata:
      labels:
        app: nginx
        version: blue
    spec:
      containers:
      - name: nginx-blue
        image: xeng/nginx-1:latest
        ports:
        - containerPort: 80
