apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-release-2000
  namespace: nginx-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name: nginx-release-2000
        image: xeng/nginx-qa:latest
        ports:
        - containerPort: 80
