apiVersion: apps/v1
kind: Deployment
metadata:
  name: other
  namespace: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: other
  template:
    metadata:
      labels:
        app: other
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name: other
        image: nginx:latest
        ports:
        - containerPort: 80
